#@data/values
---
credentials:
- env_id: "01"
  env_instance: "01"
  env_password: "ENV-PASSWORD-GOES-HERE"   
  env_cf_apiID: "CF_DEPLOYMENT_ID_GOES_HERE"
- env_id: "01"
  env_instance: "02"
  env_password: "ENV-PASSWORD-GOES-HERE"
  env_cf_apiID: "CF_DEPLOYMENT_ID_GOES_HERE"
 