#@data/values
---
credentials:
- env_id: "01"
  env_instance: "01"
  env_username: "ENV-USERNAME-GOES-HERE"
  env_password: "ENV-PASSWORD-GOES-HERE"   
  jfrog_username: "USERNAME-GOES-HERE"
  jfrog_password: "PASSWORD-GOES-HERE"   
  jfrog_url: "JFROG-URL-GOES-HERE"
- env_id: "01"
  env_instance: "02"
  env_username: "ENV-USERNAME-GOES-HERE"
  env_password: "ENV-PASSWORD-GOES-HERE"   
  jfrog_username: "USERNAME-GOES-HERE"
  jfrog_password: "PASSWORD-GOES-HERE"   
  jfrog_url: "JFROG-URL-GOES-HERE"